#!/bin/sh

get_subject() {
  if [ "$1" = "trusted" ]; then
    echo "/C=BR/ST=Sao Paulo/L=Sao Paulo/O=YARP/OU=Security/CN=127.0.0.1"
  else
    echo "/C=XX/ST=Untrusted/L=Evilland/O=Eve/OU=Haxxxxxxxx/CN=127.0.0.1"
  fi
}

# Generate two CAs: one to be considered trusted, and one that's untrusted
for type in trusted untrusted; do
  rm -rf ./ca
  mkdir -p ./ca
  mkdir -p ./ca/certs
  mkdir -p ./ca/crl
  mkdir -p ./ca/newcerts
  mkdir -p ./ca/private
  touch ./ca/index.txt

  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out ${type}-ca.key
  openssl req -new -x509 -days 12500 -key ${type}-ca.key -sha256 -out ${type}-ca.crt -subj "$(get_subject $type)"
  openssl x509 -in ${type}-ca.crt -noout -next_serial -out ./ca/serial

  openssl req -newkey rsa:2048 -keyout ${type}-cert.key -nodes -out ${type}-cert.req -subj "$(get_subject $type)"
  yes | openssl ca -config ./openssl.cnf -days 12500 -cert ${type}-ca.crt -keyfile ${type}-ca.key -out ${type}-cert.crt -infiles ${type}-cert.req
  rm ${type}-cert.req
done

rm -rf ./ca
